# Site settings
title: k2byew tries to blog
header-img: img/home-bg.jpg
email: k2byew@users.noreply.github.com
description: "random bits of stuff, left to gather dust"
baseurl: ""
url: "http://k2byew.surge.sh"
github_username:  k2byew

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# Add custom gems
gems: [jekyll-paginate]